-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 27, 2024 at 09:10 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blueroom`
--

-- --------------------------------------------------------

--
-- Table structure for table `company_data`
--

CREATE TABLE `company_data` (
  `id` int(11) NOT NULL,
  `form_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`form_data`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `company_data`
--

INSERT INTO `company_data` (`id`, `form_data`, `created_at`, `updated_at`) VALUES
(1, '{\"basics\":{\"companyName\":\"Bernard and Beck Co\",\"tradingNames\":[\"Autem necessitatibus\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 13:49:54', '2024-11-26 13:49:54'),
(2, '{\"basics\":{\"companyName\":\"Bernard and Beck Co\",\"tradingNames\":[\"Autem necessitatibus\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 13:50:03', '2024-11-26 13:50:03'),
(3, '{\"basics\":{\"companyName\":\"Bernard and Beck Co\",\"tradingNames\":[\"Autem necessitatibus\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 13:50:33', '2024-11-26 13:50:33'),
(4, '{\"basics\":{\"companyName\":\"Petersen and Benjamin LLC\",\"tradingNames\":[\"Qui sed ut debitis o\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"ANZ\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 13:52:47', '2024-11-26 13:52:47'),
(5, '{\"basics\":{\"companyName\":\"Petersen and Benjamin LLC\",\"tradingNames\":[\"Qui sed ut debitis o\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"ANZ\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 13:54:58', '2024-11-26 13:54:58'),
(6, '{\"basics\":{\"companyName\":\"Petersen and Benjamin LLC\",\"tradingNames\":[\"Qui sed ut debitis o\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"ANZ\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 13:57:12', '2024-11-26 13:57:12'),
(7, '{\"basics\":{\"companyName\":\"Proximux\",\"tradingNames\":[\"developer\'s\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Westpac\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Et quidem voluptas n\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 17:05:34', '2024-11-26 17:05:34'),
(8, '{\"basics\":{\"companyName\":\"Proximux\",\"tradingNames\":[\"\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 17:07:33', '2024-11-26 17:07:33'),
(9, '{\"basics\":{\"companyName\":\"Waters Duffy Plc\",\"tradingNames\":[\"jv\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 17:10:52', '2024-11-26 17:10:52'),
(10, '{\"basics\":{\"companyName\":\"Proximux\",\"tradingNames\":[\"vcvxz\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-26 17:48:16', '2024-11-26 17:48:16'),
(11, '{\"basics\":{\"companyName\":\"Berger and Kim Plc\",\"tradingNames\":[\"Sint sunt blanditi\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"lalipude@mailinator.com\",\"careOf\":\"Quis esse asperiores\",\"streetAddress\":\"Sint veniam omnis \",\"city\":\"Sint veniam repell\",\"postCode\":\"Perspiciatis esse \",\"serviceAddressSame\":false,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Whilemina\",\"lastName\":\"Rowe\",\"email\":\"bafekeryk@mailinator.com\",\"address\":\"Incidunt aliquid ad\",\"city\":\"Placeat consequat \",\"postCode\":\"Dolore dignissimos e\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":\"\",\"selectedDirector\":\"0\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 14:17:13', '2024-11-27 14:17:13'),
(12, '{\"basics\":{\"companyName\":\"Reid and Castaneda Co\",\"tradingNames\":[\"Aliquam consequatur\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"BNZ\"},\"address\":{\"email\":\"nyfohys@mailinator.com\",\"careOf\":\"Asperiores amet tem\",\"streetAddress\":\"Rerum corporis liber\",\"city\":\"Sit reiciendis archi\",\"postCode\":\"Omnis provident har\",\"serviceAddressSame\":true,\"communicationAddressSame\":false},\"directors\":[{\"firstName\":\"haider\",\"lastName\":\"zaman\",\"email\":\"haiderzaman1781@gmail.com\",\"address\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 14:18:07', '2024-11-27 14:18:07'),
(13, '{\"basics\":{\"companyName\":\"Martinez and Knapp Associates\",\"tradingNames\":[\"Qui labore tempora t\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"ASB\"},\"address\":{\"email\":\"xetiqe@mailinator.com\",\"careOf\":\"Esse fugiat et ipsa\",\"streetAddress\":\"Sunt cumque dolorem\",\"city\":\"Qui blanditiis ut ir\",\"postCode\":\"Eos consequat Est a\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Nomlanga\",\"lastName\":\"Brock\",\"email\":\"tojyfyw@mailinator.com\",\"address\":\"Voluptas ullam ut ma\",\"city\":\"Harum aut voluptate \",\"postCode\":\"Proident saepe amet\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 14:22:10', '2024-11-27 14:22:10'),
(14, '{\"basics\":{\"companyName\":\"Proximux\",\"tradingNames\":[\"Ipsum tempora nihil\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"ASB\"},\"address\":{\"email\":\"mazox@mailinator.com\",\"careOf\":\"Delectus tempor in \",\"streetAddress\":\"Excepturi vel et ill\",\"city\":\"Dolorum rerum ut com\",\"postCode\":\"Velit a deserunt ev\",\"serviceAddressSame\":false,\"communicationAddressSame\":false},\"directors\":[{\"firstName\":\"Martin\",\"lastName\":\"Howard\",\"email\":\"zubyxozu@mailinator.com\",\"address\":\"Vitae impedit eum r\",\"city\":\"Assumenda dolorum mi\",\"postCode\":\"Ullam aut voluptatem\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 14:23:59', '2024-11-27 14:23:59'),
(15, '{\"basics\":{\"companyName\":\"Russo and Best LLC\",\"tradingNames\":[\"Quaerat ut ullam vol\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Westpac\"},\"address\":{\"email\":\"gujyhuqoru@mailinator.com\",\"careOf\":\"Iure cillum enim et \",\"streetAddress\":\"Nostrud magni aut ra\",\"city\":\"Exercitation odit il\",\"postCode\":\"Maxime sint aut ab a\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Channing\",\"lastName\":\"Carroll\",\"email\":\"dezifeqiko@mailinator.com\",\"address\":\"Nobis ut itaque iste\",\"city\":\"Quo eius velit aliq\",\"postCode\":\"Porro natus repellen\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 14:26:16', '2024-11-27 14:26:16'),
(16, '{\"basics\":{\"companyName\":\"Bailey Valenzuela Associates\",\"tradingNames\":[\"Omnis consequat Aut\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"pamo@mailinator.com\",\"careOf\":\"Officiis laborum Mi\",\"streetAddress\":\"Sit aut ipsum cill\",\"city\":\"Rem voluptatum expli\",\"postCode\":\"Quis ratione aut qui\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Kyra\",\"lastName\":\"Battle\",\"email\":\"xosojuza@mailinator.com\",\"address\":\"Id explicabo Iusto \",\"city\":\"Eos nostrum fugiat\",\"postCode\":\"Eveniet aperiam non\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:21:54', '2024-11-27 15:21:54'),
(17, '{\"basics\":{\"companyName\":\"Proximux\",\"tradingNames\":[\"\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"\"},\"address\":{\"email\":\"haiderzaman1781@gmail.com\",\"careOf\":\"Quas fuga Voluptate\",\"streetAddress\":\"51 Ferguson Street, Awapuni, Palmerston North 4412\",\"city\":\"Palmerston North\",\"postCode\":\"4412\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Geoffrey\",\"lastName\":\"Ayala\",\"email\":\"suqip@mailinator.com\",\"address\":\"Neque nihil soluta v\",\"city\":\"Rem dolorum possimus\",\"postCode\":\"Duis amet iure sed \",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:24:40', '2024-11-27 15:24:40'),
(18, '{\"basics\":{\"companyName\":\"Proximux\",\"tradingNames\":[\"Laborum et nihil mai\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"kokaqytyq@mailinator.com\",\"careOf\":\"Quibusdam fugiat ea \",\"streetAddress\":\"Sapiente culpa a do\",\"city\":\"Et quos dolor esse e\",\"postCode\":\"Dolore vel ut minima\",\"serviceAddressSame\":true,\"communicationAddressSame\":false},\"directors\":[{\"firstName\":\"Malachi\",\"lastName\":\"Hansen\",\"email\":\"zomiliv@mailinator.com\",\"address\":\"Culpa tempora enim \",\"city\":\"Rerum ipsum voluptas\",\"postCode\":\"Recusandae Ut sed s\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:27:14', '2024-11-27 15:27:14'),
(19, '{\"basics\":{\"companyName\":\"Aguirre Shaw Inc\",\"tradingNames\":[\"Vel molestiae autem \"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"ANZ\"},\"address\":{\"email\":\"wati@mailinator.com\",\"careOf\":\"Lorem aperiam nihil \",\"streetAddress\":\"Sint fugit voluptat\",\"city\":\"Error in debitis qui\",\"postCode\":\"Molestiae quia autem\",\"serviceAddressSame\":false,\"communicationAddressSame\":false},\"directors\":[{\"firstName\":\"Walter\",\"lastName\":\"Ryan\",\"email\":\"vese@mailinator.com\",\"address\":\"Et esse aut et conse\",\"city\":\"Nobis labore tempore\",\"postCode\":\"Amet maxime lorem o\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:31:57', '2024-11-27 15:31:57'),
(20, '{\"basics\":{\"companyName\":\"Boyle and Oliver Trading\",\"tradingNames\":[\"Nostrud perferendis \"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Not Required\"},\"address\":{\"email\":\"tygohibywy@mailinator.com\",\"careOf\":\"Reprehenderit dolor \",\"streetAddress\":\"Consectetur est rep\",\"city\":\"In ut eos numquam qu\",\"postCode\":\"Reiciendis architect\",\"serviceAddressSame\":false,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Abra\",\"lastName\":\"Edwards\",\"email\":\"piky@mailinator.com\",\"address\":\"Nostrud omnis tenetu\",\"city\":\"Ipsum et ut nulla o\",\"postCode\":\"Sunt nulla rem susc\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:35:13', '2024-11-27 15:35:13'),
(21, '{\"basics\":{\"companyName\":\"Guerra and Gray Associates\",\"tradingNames\":[\"Nihil quis fuga Off\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Kiwibank\"},\"address\":{\"email\":\"sugezana@mailinator.com\",\"careOf\":\"Quod earum voluptate\",\"streetAddress\":\"Iste debitis id aut \",\"city\":\"Sunt proident pari\",\"postCode\":\"Et dolorum distincti\",\"serviceAddressSame\":false,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Samuel\",\"lastName\":\"Mcmahon\",\"email\":\"wetufujodo@mailinator.com\",\"address\":\"Nulla ut nostrud qui\",\"city\":\"Distinctio Voluptat\",\"postCode\":\"Consectetur aute es\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:35:53', '2024-11-27 15:35:53'),
(22, '{\"basics\":{\"companyName\":\"Sweeney and Livingston LLC\",\"tradingNames\":[\"Delectus esse nihi\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Westpac\"},\"address\":{\"email\":\"zygixywo@mailinator.com\",\"careOf\":\"Cupiditate voluptate\",\"streetAddress\":\"Proident animi mag\",\"city\":\"Deleniti cillum recu\",\"postCode\":\"Sapiente non id non\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Griffin\",\"lastName\":\"Soto\",\"email\":\"kimynu@mailinator.com\",\"address\":\"Pariatur Qui possim\",\"city\":\"Ut soluta veritatis \",\"postCode\":\"Qui aut et vel conse\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100}],\"shares\":{\"totalShares\":0,\"allocatedShares\":0,\"selectedDirector\":\"\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 15:37:41', '2024-11-27 15:37:41'),
(23, '{\"basics\":{\"companyName\":\"Knowles Wheeler Co\",\"tradingNames\":[\"Ea ex cumque repudia\"],\"taxOptions\":{\"IRD\":true,\"GST\":true},\"bankOption\":\"Not Required\"},\"address\":{\"email\":\"lykaka@mailinator.com\",\"careOf\":\"Quod debitis quaerat\",\"streetAddress\":\"Et id atque sunt ex\",\"city\":\"Soluta sit proident\",\"postCode\":\"Fuga Consectetur l\",\"serviceAddressSame\":true,\"communicationAddressSame\":true},\"directors\":[{\"firstName\":\"Indigo\",\"lastName\":\"Willis\",\"email\":\"piqoby@mailinator.com\",\"address\":\"Delectus ex quo per\",\"city\":\"Repellendus Magnam \",\"postCode\":\"Placeat sed harum e\",\"country\":\"NEW ZEALAND\",\"allocatedShares\":100},{\"firstName\":\"Alfreda\",\"lastName\":\"Gould\",\"email\":\"zudiqowo@mailinator.com\",\"address\":\"Est sit possimus c\",\"city\":\"Duis excepturi et ex\",\"postCode\":\"Sed excepturi non te\",\"country\":\"NEW ZEALAND\"}],\"shares\":{\"totalShares\":0,\"allocatedShares\":\"50\",\"selectedDirector\":\"1\"},\"extra\":[],\"tax\":{\"contactPerson\":\"\",\"contactPhone\":\"\",\"businessAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"postalAddress\":{\"address\":\"\",\"city\":\"\",\"postCode\":\"\"},\"taxAgent\":\"\",\"fringeBenefits\":\"\"}}', '2024-11-27 17:26:23', '2024-11-27 17:26:23');

-- --------------------------------------------------------

--
-- Table structure for table `directors`
--

CREATE TABLE `directors` (
  `id` int(11) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `street_address` text NOT NULL,
  `city` varchar(100) NOT NULL,
  `postal_code` varchar(20) NOT NULL,
  `country` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `directors`
--

INSERT INTO `directors` (`id`, `first_name`, `last_name`, `street_address`, `city`, `postal_code`, `country`, `email`, `created_at`) VALUES
(1, 'haider', 'zaman', '51 Ferguson Street, Awapuni, Palmerston North 4412', 'Palmerston North', '4412', 'NEW ZEALAND', 'haiderzaman1781@gmail.com', '2024-11-25 16:09:14'),
(11, 'Zahir', 'Mercado', 'Veritatis expedita n', 'Ut aut fugiat eos o', 'Ea ut omnis aspernat', 'NEW ZEALAND', 'quju@mailinator.com', '2024-11-25 16:24:45'),
(14, 'Alfreda', 'Albert', 'Impedit sit volupt', 'Qui ullamco iusto do', 'Rem labore consequat', 'NEW ZEALAND', 'wote@mailinator.com', '2024-11-25 16:26:35'),
(17, 'Wing', 'Woodard', 'Voluptatem in iste o', 'Voluptatum quia eos', 'Est odio nemo est e', 'NEW ZEALAND', 'horolagyd@mailinator.com', '2024-11-25 16:29:01'),
(32, 'Alana', 'Stanley', 'Dolorem aliquam mole', 'Facere quibusdam ali', 'Aut aperiam sed non ', 'NEW ZEALAND', 'zubec@mailinator.com', '2024-11-25 16:55:01'),
(33, 'Driscoll', 'Nichols', 'Aliquip et magnam di', 'Qui repellendus Fac', 'Ab occaecat sed quo ', 'NEW ZEALAND', 'jezivupysu@mailinator.com', '2024-11-25 16:55:01'),
(37, 'Candice', 'Kidd', 'Quis soluta sint ma', 'Id rerum nobis sed e', 'Ex eveniet sed aute', 'NEW ZEALAND', 'foqufy@mailinator.com', '2024-11-25 17:16:31'),
(40, 'Shafira', 'Walter', 'Sequi officiis quo a', 'Eum velit id nesciun', 'Minim tempore excep', 'NEW ZEALAND', 'vifoge@mailinator.com', '2024-11-25 17:39:15'),
(46, 'Medge', 'Doyle', 'Sit ad dolor odit it', 'Nulla dolore porro q', 'Suscipit cupidatat c', 'NEW ZEALAND', 'pana@mailinator.com', '2024-11-25 17:51:37'),
(47, 'Cruz', 'Cantu', 'Sequi corrupti duis', 'Officiis atque do no', 'Cupiditate laboriosa', 'NEW ZEALAND', 'kikubivuxi@mailinator.com', '2024-11-25 17:53:18'),
(50, 'Sharon', 'Reid', 'Nesciunt ex volupta', 'Anim est quae non i', 'Quia facilis possimu', 'NEW ZEALAND', 'tiga@mailinator.com', '2024-11-25 18:08:03'),
(52, 'Selma', 'Mills', 'Ut nisi alias adipis', 'Autem adipisicing do', 'Illum autem eum exp', 'NEW ZEALAND', 'pefebete@mailinator.com', '2024-11-25 18:10:16'),
(56, 'Eaton', 'Calderon', 'Laboris obcaecati mi', 'Dolor lorem non eius', 'Porro dolor ut sed o', 'NEW ZEALAND', 'hakobisypu@mailinator.com', '2024-11-25 18:20:44'),
(75, 'Jessica', 'William', 'Nisi quia architecto', 'Quaerat veniam reic', 'Molestiae et alias q', 'NEW ZEALAND', 'nobedoqupe@mailinator.com', '2024-11-25 18:42:37');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `company_data`
--
ALTER TABLE `company_data`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `directors`
--
ALTER TABLE `directors`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `company_data`
--
ALTER TABLE `company_data`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;

--
-- AUTO_INCREMENT for table `directors`
--
ALTER TABLE `directors`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
